version: "3.9"
volumes:
  db-store:
  psysh-store:
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    ports:
      - ${PHP_PORT:-5173}
    volumes:
      - type: bind
        source: ./contents
        target: /home/contents
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
